import Anthropic from '@anthropic-ai/sdk';
import dotenv from 'dotenv';

dotenv.config();

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

const MODEL = 'claude-sonnet-4-6';

/** Strip markdown code fences that Claude sometimes wraps JSON in. */
function extractJson(text: string): string {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) return fenced[1].trim();
  return text.trim();
}

export interface ParsedResume {
  name: string;
  email: string | null;
  phone: string | null;
  linkedin_url: string | null;
  headline: string;
  skills: string[];
  experience_years: number;
  job_types: string[];
  seniority: string;
  location: string | null;
}

export interface MatchScore {
  score: number;
  reasoning: string;
}

export interface ParsedJob {
  title: string;
  department: string | null;
  job_type: string;
  seniority: string;
  location: string | null;
  description: string;
  source_url: string | null;
}

export async function parseResume(resumeText: string): Promise<ParsedResume> {
  const prompt = `You are parsing a resume/CV. Extract the following structured data as JSON:
{
  "name": "string",
  "email": "string or null",
  "phone": "string or null",
  "linkedin_url": "string or null",
  "headline": "one-line professional summary, max 100 chars",
  "skills": ["skill1", "skill2", ...],
  "experience_years": number,
  "job_types": ["engineering", "sales", ...],
  "seniority": "junior|mid|senior|lead|director|vp|c-level",
  "location": "string or null"
}
Resume text:
---
${resumeText}
---
Return ONLY valid JSON, no other text.`;

  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 1024,
    messages: [{ role: 'user', content: prompt }],
  });

  const content = response.content[0];
  if (content.type !== 'text') {
    throw new Error('Unexpected response type from AI');
  }

  const jsonText = extractJson(content.text);
  return JSON.parse(jsonText) as ParsedResume;
}

export async function scoreMatch(
  candidate: {
    name: string;
    headline: string | null;
    skills: string | null;
    experience_years: number | null;
    job_types: string | null;
    seniority: string | null;
    location: string | null;
  },
  opportunity: {
    title: string;
    department: string | null;
    job_type: string | null;
    seniority: string | null;
    location: string | null;
    description: string | null;
  }
): Promise<MatchScore> {
  const prompt = `You are an expert recruiter evaluating candidate-job fit.
Think broadly about transferable skills.
Rate the match from 0.0 to 1.0 and explain in 1-2 sentences.
Candidate: ${JSON.stringify(candidate)}
Opportunity: ${JSON.stringify(opportunity)}
Return ONLY valid JSON: { "score": 0.0-1.0, "reasoning": "string" }`;

  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 256,
    messages: [{ role: 'user', content: prompt }],
  });

  const content = response.content[0];
  if (content.type !== 'text') {
    throw new Error('Unexpected response type from AI');
  }

  const jsonText = extractJson(content.text);
  return JSON.parse(jsonText) as MatchScore;
}

export async function draftIntroductionEmail(
  company: {
    name: string;
    contact_name: string | null;
    contact_email: string | null;
  },
  opportunity: {
    title: string;
    description: string | null;
  },
  candidate: {
    name: string;
    email: string | null;
    linkedin_url: string | null;
    headline: string | null;
    skills: string | null;
    experience_years: number | null;
  }
): Promise<{ subject: string; body: string }> {
  const prompt = `You are drafting a candidate suggestion email from a venture capitalist to a portfolio company's hiring contact. This is NOT an introduction — the candidate does not know about this email. You are suggesting a candidate for the company to evaluate.

This email is generated by an AI-powered talent matching system. Mention this transparently.

Company: ${company.name}
Contact: ${company.contact_name || 'Hiring Manager'}
Role: ${opportunity.title}
Job Description: ${opportunity.description || 'N/A'}
Candidate: ${candidate.name}
Candidate Email: ${candidate.email || 'N/A'}
Candidate LinkedIn: ${candidate.linkedin_url || 'N/A'}
Candidate Summary: ${candidate.headline || 'N/A'}
Skills: ${candidate.skills || 'N/A'}
Experience: ${candidate.experience_years || 'N/A'} years

Write a short professional email (3-5 sentences) that:
1. Addresses contact by first name
2. Mentions this comes from an AI matchmaking system
3. Mentions the specific role
4. Explains why the candidate could be a fit
5. Includes candidate's LinkedIn and email
6. Makes clear this is a suggestion

Output ONLY the email body.`;

  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 512,
    messages: [{ role: 'user', content: prompt }],
  });

  const content = response.content[0];
  if (content.type !== 'text') {
    throw new Error('Unexpected response type from AI');
  }

  const body = content.text.trim();
  const subject = `Candidate Suggestion: ${candidate.name} for ${opportunity.title} at ${company.name}`;

  return { subject, body };
}

export async function parseJobsFromPage(pageText: string): Promise<ParsedJob[]> {
  const prompt = `You are parsing a careers/jobs page. Extract all job openings as a JSON array.
For each job, capture the direct URL to the individual job posting if available.
[
  {
    "title": "string",
    "department": "string or null",
    "job_type": "engineering|sales|marketing|design|operations|finance|product|data|hr|other",
    "seniority": "junior|mid|senior|lead|director|vp|c-level",
    "location": "string or null",
    "description": "string",
    "source_url": "string or null"
  }
]
Page content:
---
${pageText}
---
Return ONLY valid JSON array.`;

  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 4096,
    messages: [{ role: 'user', content: prompt }],
  });

  const content = response.content[0];
  if (content.type !== 'text') {
    throw new Error('Unexpected response type from AI');
  }

  const jsonText = extractJson(content.text);
  return JSON.parse(jsonText) as ParsedJob[];
}
